# Generated by Django 3.0.8 on 2020-08-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Names',
        ),
    ]
