# Generated by Django 3.0.8 on 2020-09-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200909_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diffculty_Breathing', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('chest_pain', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('loss_of_Speech', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('loss_of_Taste', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('fever', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('cold', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('dry_cough', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('triedness', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('sore_throat', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('headache', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='covid_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Rather not say', 'RATHER NOT SAY')], max_length=20, null=True)),
                ('age', models.CharField(max_length=4, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=900, null=True)),
                ('phno', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=80, null=True)),
            ],
        ),
    ]
